---
# tasks file for poudriere
- name: INSTALL | install packages 
  pkgng: 
   name={{ item }}
   state=present

  with_items:
   - poudriere
   - ccache
   - dialog4ports

  tags:
   - install


# --------------------------------------------------------
- name: CREATE DIR | create dir keys,certs
  file:
   state=directory
   path={{ poudriere_ssl_dir }}/{{ item.name }}
   owner=root
   group=wheel
   mode={{ item.mode }}

  when:  poudriere_ssl_enable
  with_items:
   - { name: 'keys', mode: '0600' }
   - { name: 'certs', mode: '0644' }

  tags:
   - config

# --------------------------------------------------------
# ---- Toto bude potreba pak hodit do samotne role ?  ----
# sudo openssl genrsa -out /usr/local/etc/ssl/keys/poudriere.key 4096
# sudo openssl rsa -in /usr/local/etc/ssl/keys/poudriere.key -pubout -out /usr/local/etc/ssl/certs/poudriere.cert
# --------------------------------------------------------

# --------------------------------------------------------
- name: CREATE DIR | create dir /var/cache/ccache
  file:
   state=directory
   path={{ poudriere_CCACHE_DIR }}
   owner=root
   group=wheel
   mode=0660

  tags:
   - config

# ---------------------------------------------------------------------
- name: CONFIG | Copy template poudriere.conf
  template: >
   backup=yes 
   src=poudriere.conf.j2 
   dest=/usr/local/etc/poudriere.conf
   owner=root 
   group=wheel 
   mode=0640

  tags:
   - config
   - template


# ---------------------------------------------------------------------
- name: PREPARE | prepare jail
  shell: "poudriere jail -c -j {{ item.poudriere_name }} -v {{ item.poudriere_version }} -a {{ item.poudriere_arch }}"
  ignore_errors: yes


# ---------------------------------------------------------------------
# TOTO jeste upravit
# ---------------------------------------------------------------------     
#   with_file:
#   - poudriere_jails.yml
  with_items: 
   - { poudriere_label: "FreeBSD 10.2-RELEASE 64bit",
       poudriere_name: "freebsd:10:x86:64",
       poudriere_version: "10.2-RELEASE",
       poudriere_arch: "amd64"
      }

  tags:
   - prepare
# ---------------------------------------------------------------------
# TOTO jeste upravit
# ---------------------------------------------------------------------     






- name: PREPARE | prepare ports 
  shell: "poudriere ports -c"
  ignore_errors: yes

  tags:
   - prepare

- name: PREPARE | Update ports 
  shell: "poudriere ports -u"
  

  tags:
   - prepare
   - update

- name: PREPARE | Update jail
  shell: "poudriere jail -u -j {{ item.poudriere_name }}"
# ---------------------------------------------------------------------
# TOTO jeste upravit
# ---------------------------------------------------------------------       
  with_items: 
   - { poudriere_label: "FreeBSD 10.2-RELEASE 64bit",
       poudriere_name: "freebsd:10:x86:64",
       poudriere_version: "10.2-RELEASE",
       poudriere_arch: "amd64"
      }
# ---------------------------------------------------------------------
# TOTO jeste upravit
# ---------------------------------------------------------------------     

  tags:
   - prepare
   - update



# ---------------------------------------------------------------------
# - name: CONFIG | Copy template make.conf, pkglist
#   template: >
#    # backup=yes 
#    src=poudriere.conf.j2 
#    dest=/usr/local/etc/poudriere.conf
#    owner=root 
#    group=wheel 
#    mode=0640
# 
# # ---------------------------------------------------------------------
# # TOTO jeste upravit
# # ---------------------------------------------------------------------       
#   with_items: 
#    - { poudriere_label: "FreeBSD 10.2-RELEASE 64bit",
#        poudriere_name: "freebsd:10:x86:64",
#        poudriere_version: "10.2-RELEASE",
#        poudriere_arch: "amd64"
#       }
# # ---------------------------------------------------------------------
# # TOTO jeste upravit
# # ---------------------------------------------------------------------     
# 
#   tags:
#    - config
#    - template















# - name: Name for debug module.
#   
#   debug: var={{ zfs_set }}
#   
#   tags:
#    - config
#    - template